name: flutter_modules
description: Template of some commonly used widgets.
version: 0.0.13
homepage: https://github.com/Covisoft/flutter_modules

environment:
  sdk: ">=2.13.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
    
  another_flushbar: ^1.10.24

  camera: 0.9.1
  collection: ^1.15.0

  dio: ^4.0.0
  equatable: ^2.0.3
  extended_image: any
 

  flutter_bloc: ^7.3.1
  flutter_screenutil: ^5.0.1
  flutter_svg: ^0.22.0

  google_fonts: ^2.0.0

  intl_phone_number_input:
    git:
      url: https://github.com/Honghm/flutter_packages
      path: intl_phone_number_input

  libphonenumber_plugin: ^0.2.3

  path: ^1.8.0
  path_provider: any
  provider: any
  photo_manager: ^1.3.1
  
 
  uuid: ^3.0.4
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^2.4.0
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  uses-material-design: true
 # To add assets to your package, add an assets section, like this:
  assets:
     - assets/flags/
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: CustomIcons
      fonts:
        - asset: assets/fonts/CustomIcons.ttf
    - family: ShapeIcons
      fonts:
        - asset: assets/fonts/ShapeIcons.ttf
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
